import "./global.scss";
import RestaurantHeader from "./_components/RestaurantHeader";
import RestaurantFooter from "./_components/RestaurantFooter";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <RestaurantHeader />
        <main>{children}</main>
        <RestaurantFooter />
      </body>
    </html>
  );
}
